services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: build
    command: pnpm run start:dev
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.build.json:/app/tsconfig.build.json
      - ./nest-cli.json:/app/nest-cli.json
      - /app/node_modules
      - /app/certs
      - /app/schemas
      - /app/dist
